controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homeController: 
    path: /hello
    controller: App\Controller\HomeController::index    
